[package]
name = "muks-installer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
anyhow.workspace = true
muks-adapters = { path = "../muks-adapters" }
muks-common = { path = "../muks-common" }
serde.workspace = true
serde_json.workspace = true
